##########################
# # # DEVICE COUNTER # # #
##########################

#################
# # LIBRARIES # #
#################
import json
import ast
import time
import pandas as pd
import os

########################
# # GLOBAL VARIABLES # #
########################

# PATH DATASET
# Insert the path of the dataset file (it must be a json file)
PATH_DATASET_1 = "json_file_example.json"


# PATH DATASET LIST
# Insert the name of the dataset in the same order as the path
DATASET_NAME_LIST = ['Dataset_A']
PATH_DATASET_LIST = [PATH_DATASET_1]

'''
# If you intend to use more of one dataset use this instead of the code above
# You can add as many dataset as you want, just follow the scheme below

PATH_DATASET_1 = ""
PATH_DATASET_2 = ""
PATH_DATASET_3 = ""
# PATH DATASET LIST
DATASET_NAME_LIST = ['', '', '']
PATH_DATASET_LIST = [PATH_DATASET_1, PATH_DATASET_2, PATH_DATASET_3]
'''

# PARAMETER FOR THE "filter_function"
# I suggest to change it only if you want to make some experiments
PARAMETER_FILTER_FUNCTION = 0.8 #(It must be between 0 and 1)

# PATH OF THE RESULTS FILE (.csv)
# Insert the path where you want to save the results
PATH_RESULTS_CSV = "Results.csv"
PATH_EXEC_TIME_CSV = "Execution_time.csv"

# PARAMETERS FOR THE DISEQ FUNCTION (THEY'RE USED IN THE BLOCK 2)
# I suggest to change it only if you want to make some experiments
DISEQ_UPPER_LIMIT = 80 # Upper limit
DISEQ_MANC = 1 # Constant used when one of the features is missing
DISEQ_SIM = 2 # Constant used when the value of a feature of two burst are similar (only used when the value is a list)
DISEQ_NUM = 13 # Constant used when the value of a feature of two burst are different


#################
# # FUNCTIONS # #
#################

########################################################
# VERIFY THE EXISTENCE OF A FEATURE AND RETURN ITS VALUE
# Take as input the feature and the sub-dictionary of the burst

MISSING_VALUE = 12345
def existence_check(feature, subdata):
    if feature in subdata:
        if type(subdata[feature]) == str:
            return ast.literal_eval(subdata[feature]) # Return the value as a list
        else:
            if int(subdata[feature]) == 0: # If the value of the feature is 0
                return MISSING_VALUE
            else:
                return int(subdata[feature]) # Return the numerical value (int) of the feature
    else:
        return int(MISSING_VALUE) # If the feature is not present

#####################################
# VERIFY IF A IS A SUBLIST OF B (A<B)
def is_sublist(A, B):
    n, m = len(A), len(B)
    for i in range(m - n + 1):
        if B[i:i+n] == A:
            return True
    return False

##################
# FORMAT THE TABLE
# Set the first row as header and the first column as index

def table_formatting_function(df, data):

    # add an index and a header
    list_mac = list(data.keys()) # mac addresses list
    len_mac_address_list = len(list_mac) # len list mac address
    list_mac.pop(len_mac_address_list-1)
    #print('list mac', list_mac)

    # 1. Remove the first row 
    df = df.iloc[1:]

    # 2. The first column become the index
    df = df.set_index(df.columns[0])  

    # 3. The first row is the header
    df.columns = list_mac

    return df

'''
#This method doesn't work anymore

##############################
# FIXED MAC ADDRESS FILTERINIG
# Take as input the dataset and return the number of devices that have a fixed MAC Address
# In the process it remove from data the burst generated by the devices that have a fixed MAC Address

def filtro_mac(data):
    MAC_addr = list(data.keys()) # MAC Address list
    num_dev_MAC_fixed = 0
    for mac in MAC_addr:
        # 1. Define your hex number (can be with or without the '0x' prefix)
        eight_bitmac_hex = '0x' +mac[:2]
        # 2. Convert hex to an integer
        num_int = int(eight_bitmac_hex, 16)

        # 3. Transform to a binary string (for visual verification)
        binary_string = bin(num_int)[2:].zfill(8)
        #print(f"Binary representation: {binary_string}")

        # Value bit 7
        bit_7_str = binary_string[-2]
        #print(bit_7_str)

        if bit_7_str == '0':
            del data[mac] # Delete from data the burst
            num_dev_MAC_fixed += 1
            #print(binary_string)
    
    return (num_dev_MAC_fixed)
'''

###########
# BLOCK 1 #
###########


# LIST OF FEATURE USED IN THE BLOCK 1
LIST_FEATURE_BLOCK_1 = ['ie1', 'ie50', 'ie45_ampduparam', 'ie45_capabilities', 'ie45_mcsset_highestdatarate',
                   'ie127_0', 'ie221_oui_0', 'ie221_type_0', 'ie221_oui_1', 'ie221_type_1', 'ie191', 'ie45_rxbitmask_32', 
                   'ie45_rxbitmask_8to15', 'ie221_oui_2', 'ie127_1', 'ie221_type_2', 'ie221_type_3', 'ie45_rxbitmask_33to38',
                   'ie45_rxbitmask_0to7', 'ie107_access_network_type', 'ie107_uesa', 'ie107_internet']

# RETURN THE VALUE OF DEVICES RESPONSABLE FOR THE GENERATION OF BURST WITH THE SAME VALUE OF THE FEATURES
# Take as input the list of the ratios between num_packets and delta_time
def function_group (ratios_list):
    ratios_list = sorted(ratios_list) # Sort the list
    group = [[ratios_list[0]]]
    i = 0
    threshold = 5
    for num in ratios_list[1:]:
        if num - group[-1][-1] <= threshold:
            group[-1].append(num)
        else:
            group.append([num])
        # threshold calculation
        threshold = (num - ratios_list[i])*5
        if threshold < 0.5:
            threshold = 0.5
        i+=1
    list_len_groups = []
    for sublist in group:
        list_len_groups.append(len(sublist))
    list_len_groups, group  = zip(*sorted(zip(list_len_groups, group), reverse = True))
    # Counting devices
    i = 1
    n_disp = 1
    list_len_groups = list(list_len_groups)
    n = 0
    if min(group[n]) == 0 and max(group[n]) == 0:
        list_len_groups.pop(0)
    if len(list_len_groups) != 0: 
        while i < len(list_len_groups):
            if list_len_groups[0]*PARAMETER_FILTER_FUNCTION <= list_len_groups[i]:
                n_disp += 1
            else:
                break
            i += 1
    return n_disp   

# DATASET REDUCTION FUNCTION
# Take as input data, step end dict_device
# In the end it return dict_device 
# Remove from data the burst with the same value of the features, remaning only different bursts
# In dict_device the different bursts are linked with the number of devices probably responsable for the generation of burst with the same value of the features
def funct_data_reduction (data, step, dict_device): #Prende in ingresso il dataset e il numero di passaggi che deve essere inizializzato a 0

    if len(data)==step: # end condition
        return dict_device

    else:
        #equal_brust_counter = 0 # It's used to know the number of times a burst with that structure is repeated
        MAC_addr = list(data.keys()) #list MAC addresses
        len_mac_address_list = len(MAC_addr) # len list MAC addresses
        
        mac_0 = MAC_addr[step] # mac ref
        subdata_a = data[MAC_addr[step]] # subdictionary that will be compared with the others
        values_a = [] # list of values of the feautures
        time = subdata_a['delta_time'] # value of delta_time
        num_packets = subdata_a['num_packets'] # value of num_packets
        if time != 0:
            rapporto = num_packets/time
        else: # if time is 0
            time = 0.0000000000000009
            rapporto = num_packets/time
        lista_rapporti = [rapporto]
        
        for f in LIST_FEATURE_BLOCK_1: # Add the values of the features in the list values_a
            ver_a = existence_check(f, subdata_a)
            values_a.append(ver_a)
        j= step + 1 # initialisation  j
        while j<len_mac_address_list: # In this cicle the features of every burst are compared
            if MAC_addr[0] != MAC_addr[j]: # check if the MAC addresses are the same
                subdata = data[MAC_addr[j]] 
                sum_difference = 0 # initialisation sum of the difference between the features
                h = 0 #  It's needed as index for the list 'values_a'
                for f in LIST_FEATURE_BLOCK_1: # Cicle where the values are compared
                    ver_b = existence_check(f, subdata) # Value of feature f in the burst with MAC_addr[j] as MAC
                    if type(values_a[h]) == list and type(ver_b) == list: # In the event the two features are list type 
                        difference = abs(sum(values_a[h]) - sum(ver_b))
                    elif type(values_a[h]) != type(ver_b): # In the event of different types
                        sum_difference = 5000
                        break
                    else: # In the event of int type
                        difference = abs(values_a[h] - ver_b)
                    sum_difference += difference
                    h += 1
                    if sum_difference != 0: # If sum is different from 0
                        break
                if sum_difference == 0: # If all the features are alike
                    del data[MAC_addr[j]] # Delete the burst duplicated
                    #count_probe_uguali += 1 # Add 1 to the count of equal bursts
                    time = subdata['delta_time']
                    num_packets = subdata['num_packets']
                    # num_packets delta_time ratio
                    if time != 0: 
                        rapporto = num_packets/time
                    else:
                        time = 0.0000000000000001
                        rapporto = num_packets/time
                    lista_rapporti.append(rapporto)
                j += 1 # Add 1 to go to the next burst
            else: # In the event the MAC address are equal
                j += 1 
        
        step += 1 # To go to the next burst ref
        dict_device[str(mac_0)] = function_group(lista_rapporti) # Add the burst ref to the dictionary
        return funct_data_reduction(data, step, dict_device) # The function is called back



###########
# Block 2 #
###########

# CREATE A TABLE THAT LINK THE INEQUALITY VALUE BETWEEN TWO BURST FOR EVERY BURST
def inequality_matrix_creator(data, n):

    # List of features used by the Block 2
    list_feature_Block_2 = ['ie1', 'ie50', 'ie45_ampduparam', 'ie45_capabilities', 'ie45_mcsset_highestdatarate',
                        'ie127_0', 'ie221_oui_0', 'ie221_type_0', 'ie221_oui_1', 'ie221_type_1', 'ie191', 'ie45_rxbitmask_32', 
                        'ie45_rxbitmask_8to15', 'ie221_oui_2', 'ie127_1', 'ie221_type_2', 'ie221_type_3', 'ie45_rxbitmask_33to38',
                        'ie45_rxbitmask_0to7', 'ie107_access_network_type']


    list_mac = list(data.keys()) # list MAC Addresses
    len_mac_address_list = len(list_mac) # len list MAC Addresses
    if len_mac_address_list == 1: # End condition
        return [list_mac]
    else:
        if n==0: # First condition, it create the header of the table
            data = data.copy()
            index = ['mac']
            list_mac.pop(len_mac_address_list-1)
            index += list_mac
            return [index] + inequality_matrix_creator(data, 1)
        else: # Here the matrix is created
            values_a = []
            mac_0 = list_mac[len_mac_address_list-1] # it starts from the last row
            subdata = data[mac_0] 
            for f in list_feature_Block_2: # Add the value of the features in values_a
                ver = existence_check(f, subdata)
                values_a.append(ver)
            inequality_vector = [mac_0] # The first element is the MAC
            list_mac.pop(len_mac_address_list-1) # The last value of the list_mac is removed
            for mac in list_mac: 
                inequality_value = 0 # Value of the inequality of two burst. Is initialisated to 0
                subdata_b = data[mac] # Subdata burst in comparison
                h=0 # index for the list values_a
                for feature in list_feature_Block_2:
                    valori_b = existence_check(feature, subdata_b)
                    if type(valori_b) == list and type(values_a[h]) == list: # In the event of both being list type
                            if feature == 'ie127_0': # case feature ie127_0
                                if len(values_a[h]) == len(valori_b):
                                    subtraction = [abs(g - k) for g, k in zip(values_a[h], valori_b)] # subtraction member by member # it's a list
                                    if sum(subtraction) != 0: # Case not every subtraction is 0 
                                        if subtraction.count(0) >= (len(subtraction)-2): # if there are less than two values different from 0
                                            difference_value = 'similar'
                                        else: # nore that two values different from 0
                                            difference_value = 'different'
                                    else: # if every value in the subtraction list is 0
                                        difference_value = 'equal'
                                else: # case the length of the two lists are different
                                    difference_value = 'different'
                            elif feature == 'ie1' or feature == 'ie50': # case feature ie1 o ie50
                                if len(values_a[h]) == len(valori_b): # if the length are equal
                                    subtraction = sum([abs(g - k) for g, k in zip(values_a[h], valori_b)]) # calculate the difference between the two lists
                                    if subtraction == 0:
                                        difference_value = 'equal'
                                    else:
                                        difference_value = 5000
                                elif len(values_a[h]) < len(valori_b): # if the length of 'a' is less than 'b'
                                    if is_sublist(values_a[h], valori_b) == True: # case 'b' is a sublist of 'a'
                                        difference_value = 'similar'
                                    else:
                                        sum_n = 0
                                        for x in values_a[h]: # search if the values in the list_a are present in the list_b
                                            if x not in valori_b:
                                                sum_n += 1
                                        if sum_n != 0:
                                            difference_value = 'different'
                                        else:
                                            difference_value = 'similar'
                                else: # if the length 'a' is more than 'b'
                                    if is_sublist(valori_b, values_a[h]) == True: # case 'a' is a sublist of 'b'
                                        difference_value = 'similar'
                                    else:
                                        sum_n = 0
                                        for x in valori_b:
                                            if x not in values_a[h]: # search if the values in the list_b are present in the list_a
                                                sum_n += 1
                                        if sum_n != 0:
                                            difference_value = 'different'
                                        else:
                                            difference_value = 'similar'
                            else: # for all others type list features
                                subtraction = abs(sum(valori_b) - sum(values_a[h]))
                                if subtraction != 0:
                                    difference_value = 'different'
                                else:
                                    difference_value = 'equal'
                    elif type(values_a[h]) == int and type(valori_b) == int: # case both type int
                        if (values_a[h] == MISSING_VALUE and valori_b == MISSING_VALUE): # case both not present
                            difference_value = 'equal'
                        elif (values_a[h] != MISSING_VALUE and valori_b == MISSING_VALUE): # case value-missing
                            difference_value = 'missing'
                        elif (values_a[h] == MISSING_VALUE and valori_b != MISSING_VALUE): # caso missing-value
                            difference_value = 'missing'
                        else: # case value-value
                            subtraction = abs(values_a[h] - valori_b)
                            if subtraction !=0:
                                difference_value = 'different'
                            else:
                                difference_value = 'equal'
                    else: # case different type
                        if type(values_a[h]) == list:
                            if valori_b == MISSING_VALUE: #if 'b' is missing
                                difference_value = 'missing'
                            else:
                                sum_var = sum(values_a[h])
                                subtraction = abs(sum_var - int(valori_b))
                                if subtraction !=0:
                                    difference_value = 'different'
                                else:
                                    difference_value = 'equal'
                        elif type(valori_b) == list:
                            if values_a[h] == MISSING_VALUE: # if 'a' is missing
                                difference_value = 'missing'
                            else:
                                sum_var = sum(valori_b)
                                subtraction = abs(sum_var - int(values_a[h]))
                                if subtraction !=0:
                                    difference_value = 'different'
                                else:
                                    difference_value = 'equal'
                    # Here are added the value of inequality between two feature
                    if difference_value != 'equal' and difference_value != 'missing' and difference_value != 'similar':
                        inequality_value += DISEQ_NUM
                    elif difference_value == 'missing':
                        inequality_value += DISEQ_MANC
                    elif difference_value == 'similar':
                        inequality_value += DISEQ_SIM
                    h += 1 # change feature
                    if inequality_value > DISEQ_UPPER_LIMIT:
                        break
                if inequality_value <= DISEQ_UPPER_LIMIT:
                    inequality_vector.append(round(inequality_value, 2))
                else:
                    inequality_vector.append(None)
            #print(inequality_vector)
            del data[mac_0]
            return [inequality_vector] + inequality_matrix_creator(data, 1)

#################
# BLOCCO 3 v9.0 #
#################

# CREATE A TABLE THAT LINK EVERY BURST TO THE BURST WITH WHOM HAVE THE SMOLLEST INEQUALITY VALUE 
def min_table_creator(df): # df is the table create in the block 2
        
    index_df = df.index # idex of the df table

    #Create a dictionary. It will be our table
    dict_min = {'Burst_ref': [], 'Burst_min': [], 'Value_min': []}
 
    # cicle for every row in df
    for row in index_df:
        couple_row = df.loc[[row]].stack()
        if row in df.columns:
                couple_coluns = df[[row]].stack()
                couple = pd.concat([couple_row, couple_coluns])
        else:
            couple = couple_row
        #print (couple)
        min_couple = couple.min() # min couple
        index_min_couple = couple.idxmin() # find the min burst
        dict_min['Burst_ref'].append(row)  
        if index_min_couple[0] == row:
            dict_min['Burst_min'].append(index_min_couple[1])
        else:
            dict_min['Burst_min'].append(index_min_couple[0])
        dict_min['Value_min'].append(min_couple)
    
    # Create a pandas dataframe from dict_min
    table_burst_min = pd.DataFrame(dict_min)
    #print(table_burst_min)

    return table_burst_min

def device_couter(table_burst_min, dict_devices): #def device_couter(table_burst_min, n_devices_MAC_fixed, dict_devices):

    index_table = table_burst_min.index
    num_devices = 0  # n_devices_MAC_fixed # numer of devices. Initialisated to the number of dev with the MAC fixed
    burst_seen = [] # save the burst already seen
    for index_row in index_table: # cicle for every row of the table
        burst_ref = table_burst_min.loc[index_row, 'Burst_ref'] # burst_ref
        if burst_ref not in burst_seen: # check if burst_ref has not already been seen
            burst_seen.append(burst_ref) # add burst_ref to burst_seen
            burst_min_ref = table_burst_min.loc[index_row, 'Burst_min'] # bust min of burst_ref
            if burst_min_ref not in burst_seen: # check if burst_min has not already been seen
                burst_min_min = table_burst_min.loc[table_burst_min['Burst_ref'] == burst_min_ref, 'Burst_min'].iloc[0] # bust min of burst_min_ref
                if burst_ref == burst_min_min: # if burst_ref is equal to burst_min_min
                    num_devices += max(dict_devices[burst_ref], dict_devices[burst_min_ref]) # max device of the two bursts
                    burst_seen.append(burst_min_ref) # add burst_min_ref to burst_seen
                else: 
                    num_devices += dict_devices[burst_ref]
            else:
                num_devices += dict_devices[burst_ref]
    return num_devices # total number of devices

################################
# REAL NUMBER OF DEVICES COUNTER 

# Take as input data and return the real number of devices  
def real_device_counter(data):
    MAC_addr = list(data.keys())
    label_list  = []
    i=0
    while i < len(MAC_addr):
        subdata = data[MAC_addr[i]]
        label_list.append(subdata['label'])
        i += 1
    return len(set(label_list))


#################
# #  PROGRAM  # #
#################

start_time = time.perf_counter() #start time program

print('Device counter v9.0')

header_result_matrix = ['Dataset', 'Burst in the dataset', 'Devices counted',
                         'Execution time']

results_table = [header_result_matrix]

header_time_matrix = ['Dataset', 'Time Block 1', 'Time Block 2', 'Time Block 3', 'Total execution time']

time_table = [header_time_matrix]

n_cicle = 0 # Number of times the for cicle is executed
for path_dataset in PATH_DATASET_LIST: # cicle for every dataset

    start_dataset = time.perf_counter() # start time dataset
    results_vector = [DATASET_NAME_LIST[n_cicle]] # vector for the result in this dataset
    time_vector = [DATASET_NAME_LIST[n_cicle]] # vector of times in this dataset
    print(DATASET_NAME_LIST[n_cicle]) 
    #Import dataset
    with open(path_dataset, 'r') as file:
        data = json.load(file)

    
    burst_in_the_dataset = len(list(data.keys())) # number of burst in the dataset
    results_vector.append(burst_in_the_dataset)


    '''
    # Fixed MAC address devices filtering
    n_dev_MAC_fixed = filtro_mac(data)
    '''

    # Dataset reduction
    dict_n_dev = funct_data_reduction(data, 0, {}) # it's a dictionary
    
    print ('Len dictionary',len(list(dict_n_dev.keys())),'\n') #number of bursts with different value of the features
    
    start_normal = time.perf_counter() # start time block 2 normal version

    # NORMAL VERSION #
    print ('NORMAL VERSION', '\n')
    matrix = inequality_matrix_creator(data, 0) # inequality matrix
    df = pd.DataFrame(matrix)
    df.reset_index(drop=True, inplace=True)
    
    #print(df)

    # Create the header and the index
    df = table_formatting_function(df, data)

    #print(df)

    start_block3 = time.perf_counter() #start time block 3

    min_table = min_table_creator(df)
    devices_foud = device_couter(min_table, dict_n_dev) # devices_foud = device_couter(min_table, n_dev_MAC_fixed, dict_n_dev)
    end_block_3 = time.perf_counter()
    
    print ('Device found', devices_foud)
    time_block_1 = start_normal-start_dataset
    time_block_2 = start_block3 - start_normal
    time_block_3 = end_block_3 - start_block3
    time_total = time_block_1 + time_block_2 + time_block_3
    time_vector.append(round(time_block_1, 3))
    time_vector.append(round(time_block_2, 3))
    time_vector.append(round(time_block_3, 3))
    time_vector.append(round(time_total, 3))
    print("Time Block 1", time_block_1)
    print("Time Block 2", time_block_2)
    print("Time Block 3", time_block_3)
    print("Time total", time_total)
    
    end_dataset = time.perf_counter()

    # Add to results_vector all the results
    results_vector.append(devices_foud)
    
    results_vector.append(round(end_dataset-start_dataset, 3))

    time_table.append(time_vector) # append to the time_table the time_vector
    results_table.append(results_vector) # append to the results_table the results_vector

    n_cicle += 1


## Conversion to a csv file from the results_table
results_table = pd.DataFrame(results_table).T
results_table.reset_index(drop=True, inplace=True)
print ('\nTable results')
print(results_table.to_string())
results_table.to_csv(PATH_RESULTS_CSV, index=False, header=False)
os.startfile(PATH_RESULTS_CSV) #open the results_table file

## Conversion to a csv file from the time_table
time_table = pd.DataFrame(time_table).T
time_table.reset_index(drop=True, inplace=True)
print ('\nTime table')
print(time_table.to_string())
time_table.to_csv(PATH_EXEC_TIME_CSV, index=False, header=False)
os.startfile(PATH_EXEC_TIME_CSV) #open the time_table file

end_time = time.perf_counter()

# Print the total execution time
print("Total time:", end_time - start_time, "seconds")
